### ISSUE TITLE
Issues with Exoplayer since update on Android 11

### ISSUE THREAD

**Issue by TubaApollo** [HelloVolla/volla-os-beta-test#68]
Good Evening,
i can't 100% place it, but i think that since the update to android 11 these problems occur with apps that use exoplayer, I think it also has something to do with the media type since newpipe works without any problems.. But in the other cases I get the following error after about 10 seconds after pausing the video: ERROR_CODE_DECODING_FAILED. 
![Screenshot_20220527-223903_Aliucord_1](https://user-images.githubusercontent.com/86665265/170786529-f5621fcf-77a3-4bd6-a30c-c37c93786f55.png)
In addition, I have when playing 1080p videos enormous performance drops, which means: The lags are so extreme, the video is not watchable (with vlcplayer I don't have such problems), but that might also be due to the hardware. I have written with one of the devs from one of the app, who said that probably at most an android update could fix this.
I have this issue with multiple apps which use exoplayer (with the same error), so thats why I am asking here now. Does anyone have an idea how this could be fixed? Or maybe experienced the same problem? My device is btw the (normal) "Volla Phone".
Thank you in advance, and for the all in all great android 11 update!

**Comment by wurzer** [comment]
Android 11 offers many innovations and changes that app manufacturers have to adapt to. Unfortunately, we cannot make any statements about third-party applications like Exoplayer. I recommend that you contact the Exoplayer development team regarding Android 11.

**Comment by TubaApollo** [comment]
I see, I will try to create an ticket there, I thought that it is more likely that its something android side. Since so many apps use exoplayer, and other people probably also would face this issue.
Altough thanks for clarifying this and wish me luck.

**Comment by wurzer** [comment]
I have tested today a 1080p video of Youtube in our browser on devices with Volla OS 10 and Volla OS 11.1. On both devices, the video is running smoothly. Yesterday I could reproduce a stream with some interruptions. I assume it can be related to the bandwidth and the codec. Anyway I have also addressed your inquiry to our developer team.

**Comment by TubaApollo** [comment]
Sounds great, maybe I should try to reinstall the operating system. I recognised I also have this problem with newpipe:
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=xO5NYQB9qIo
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1177)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
	... 5 more

```
</details>
<hr>
No idea if this helps, but if I am the only one with problems I would guess its on my end.

**Comment by TubaApollo** [comment]
I did a complete reinstallation of the VollaOS.
On the clean OS (11.1) and only NewPipe installed i still can't play 1080p smoothly, also i still get the same errors when pausing the video.
720p videos seem to play smoothly but i cant really imagine that this is a hardware limitation.
It makes videos unwatchable outside of vlc, which seems to work fine also with 1080p? 
I have no idea what i else can try.

**Comment by wurzer** [comment]
Unfortunately this is an issue of the app and not of the operating system. However we will provide a performance optimization for video playback with the next system update.

**Comment by TubaApollo** [comment]
Sounds great!
I also faced this issue with other apps which used exoplayer.
Thank you for looking into this.
